option(
    'static',
    type: 'boolean',
    value: false,
    description: 'build a statically linked xpt executable.',
)
option(
    'networking',
    type: 'feature',
    value: 'enabled',
    description: 'build xpt with networking support.',
)
option(
    'ebt',
    type: 'feature',
    value: 'enabled',
    description: 'ebt build system.',
)

option(
    'doc',
    type: 'feature',
    value: 'enabled',
    description: 'xpt/ebt documentation.',
)

option(
    'ebt_only',
    type: 'feature',
    value: 'disabled',
    description: 'only build ebt.',
)

option(
    'tests',
    type: 'feature',
    value: 'enabled',
    description: 'run the test suite.',
)
option(
    'libxpt',
    type: 'feature',
    value: 'enabled',
    description: 'build the libxpt library.',
)
option(
    'xpt',
    type: 'feature',
    value: 'enabled',
    description: 'build the xpt binary.',
)
