.Dd August 4, 2026
.Dt LIBXPT 3
.Os

.Sh NAME
.Nm libxpt
.Nd xpt package management library

.Sh LIBRARY
.Lb libxpt

.Sh SYNOPSIS
.In xpt/xpt.h

.Sh DESCRIPTION

libxpt exposes a public API for managing installed packages, handling repositories, resolving dependencies and accessing the xpt package databases.

.Sh SEE ALSO
.Xr xpt 8
