.Dd August 4, 2026
.Dt LIBXPT 3
.Os

.Sh NAME
.Nm libxpt
.Nd package management library

.Sh LIBRARY
.Lb libxpt

.Sh SYNOPSIS
.In xpt/xpt.h

.Sh DESCRIPTION

.Nm
provides the core package management functionality used by
.Xr xpt 8 .

.Bl -bullet

.It
package installation and removal;

.It
package database access;

.It
repository access;

.It
dependency resolution;

.It
package metadata and manifests;

.It
package file tracking; and

.It
package database locking.

.El

.Sh SEE ALSO
.Xr mkfhs 1 ,
.Xr ebs 5 ,
.Xr ecw 8 ,
.Xr ebs 1 ,
.Xr xpt.manifest 5 ,
.Xr xpt.tree 5 ,
.Xr xpt 8
.Sh LICENSE
BSD-3-Clause, see the source code for details.
