.Dd August 4, 2026
.Dt LIBXPT 3
.Os

.Sh NAME
.Nm libxpt
.Nd xpt package management library

.Sh LIBRARY
.Lb libxpt

.Sh SYNOPSIS
.In xpt/xpt.h

.Sh DESCRIPTION

libxpt exposes a public API for managing installed packages, handling repositories, resolving dependencies and accessing the xpt package databases.

.Sh SEE ALSO
.Xr mkfhs 1 ,
.Xr ebs 5 ,
.Xr ecw 8 ,
.Xr ebs 1 ,
.Xr xpt.manifest 5 ,
.Xr xpt.tree 5 ,
.Xr xpt 8
.Sh LICENSE
BSD-3-Clause, see the source code for details.
