.Dd August 2026
.Dt MKFHS 1
.Os
.Sh NAME
.Nm mkfhs
.Nd create a 
.Xr hier 7
directory tree layout
.Sh SYNOPSIS
.Nm
.Op Ar rootfs
.Op Ar arch
.Sh DESCRIPTION
.Nm
is a shell script that generates a 
.Xr hier 7
root filesystem tree inside the
.Ar rootfs
directory.
.Pp
If
.Ar rootfs
is not specified, the script will use the current directory.
If
.Ar arch
is not specified, the script will use the system's architecture.
.Pp
If
.Ar arch
is
.Cm x86_64 ,
a
.Pa lib64
directory will be created and symlinked into the root.
.Pp
.Nm
is part of ebt build tools
.Pq Nm ebt .
.Sh COMMANDS
.Bl -tag -width Ds
.It Cm help
print usage information to the screen.
.El
.Sh SEE ALSO
.Xr ebs 1 ,
.Xr ebs 5 ,
.Xr ecw 8 ,
.Xr libxpt 3 ,
.Xr xpt.manifest 5 ,
.Xr xpt.tree 5 ,
.Xr xpt 8

.Sh LICENSE
BSD-3-Clause, see the source code for details.
